export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const APP_SUBSCRIPTION_ORDERS_MODEL = 'APP_SUBSCRIPTION_ORDERS_MODEL';
export const APP_SUBSCRIPTION_ORDERS_SCHEMA = 'app_subscription_orders';
