name: Deploy via Lambda

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
  deploy:
    name: deploy@AWS-Lambda
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && npm run build
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        PORT: ${{ secrets.PORT }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        S3_COURSE_RECEIPT_BUCKET: ${{ secrets.S3_COURSE_RECEIPT_BUCKET }}