export const routes = {
  video: 'video',
  account: 'account',
  device: 'device',
  auth: 'auth',
  plan: 'plan',
  playlist: 'playlist',
  subscription: 'subscription',
  tag: 'tag',
  training: 'training',
  category: 'category',
  history: 'account/:accountId/history',
  videoGroup: 'video-group',
  videoSubgroup: 'video-subgroup',
  healthcheck: 'healthcheck',
  objectives: 'objectives',
  medicalRestrictions: 'medical-restrictions',
  accountInterests: 'account-interests',
  payment: 'payment',
  webhook: 'webhook',
  news: 'news',
  professional: 'professional',
} as const
